server.port=8080
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/otp_service}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql
app.jwt.secret=${APP_JWT_SECRET:local-dev-super-secret-change-before-prod}
app.jwt.ttl-minutes=60
app.otp.expire-scan-ms=30000
logging.level.com.promoit.otp=INFO
